// Code generated by MockGen. DO NOT EDIT.
// Source: user_service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"
	entity "zangetsu/internal/domain/entity"

	gomock "github.com/golang/mock/gomock"
)

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// RegistrationByGmail mocks base method.
func (m *MockIUserService) RegistrationByGmail(user *entity.UserRegistrationModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegistrationByGmail", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegistrationByGmail indicates an expected call of RegistrationByGmail.
func (mr *MockIUserServiceMockRecorder) RegistrationByGmail(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegistrationByGmail", reflect.TypeOf((*MockIUserService)(nil).RegistrationByGmail), user)
}

// SignUp mocks base method.
func (m *MockIUserService) SignUp(user *entity.UserViewModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockIUserServiceMockRecorder) SignUp(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockIUserService)(nil).SignUp), user)
}
